x-veld:
  code:
    about:
      description: "apply NER models on linkedcat data for usage of the inferenced entites in the 
        AKP project"
      topics:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"

services:
  veld:
    build: .
    command: jupyter notebook --ip='*' --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/
    environment:
      input_model: null
      input_solr_core_url: null
      output_csv_file: null

