x-veld:
  code:
    # TODO
    about:
      description:
      topics:

services:
  veld:
    build: .
    command: jupyter notebook --ip='*' --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    # TODO: check if this work dir is necessary
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/
    environment:
      input_model: null
      input_solr_core_url: null
      output_csv_file: null

