x-veld:
  code:
    about:
      description: "apply NER models on linkedcat data for usage of the inferenced entites in the 
        AKP project"
      topics:
        - "NLP"
        - "Machine learning"
        - "Named entity recognition"

    inputs:
      volume: /veld/input/
      file_formats: "spacy model"
      contents:
        - "NLP model"
        - "NER model"

    outputs:
      volume: /veld/output/
      file_formats: "csv"
      contents:
        - "inferenced NLP data"
        - "NLP data"
        - "NER data"

    environment:
      solr_core_url:
        description: "url pointing to a solr core from where text data should be loaded"
        type: url
      out_csv_file: 
        description: "inferenced NLP / NER data."
        type: file
        volume: /veld/output/

services:
  veld:
    build: .
    command: jupyter notebook --ip='*' --allow-root --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src:/veld/code/
    environment:
      solr_core_url: null
      out_csv_file: null

